### ISSUE TITLE
deployment issue with truffle teams - fatal error: libudev.h: No such file or directory

### ISSUE THREAD

**Issue by selimerunkut** [trufflesuite/truffle-teams#21]
Getting this error from truffle build

`prebuild-install WARN install libusb-1.0.so.0: cannot open shared object file: No such file or directory
make: Entering directory '/home/builduser/teams_workingdir/repo/node_modules/node-hid/build'
CC(target) Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o
../hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
#include <libudev.h>`

Complete Log:
```
truffle-teams-ci: Build Number: 0543b96c-a25a-42bd-8087-6740f987faec added to queue...

truffle-teams-ci: Build request starting...

truffle-teams-ci: Installing Truffle...

truffle-teams-ci: Preparing working environment...

truffle-teams-ci: Executing build command `mkdir -p ${HOME}/teams_workingdir`

truffle-teams-ci: Executing build command `git clone https://github.com/overqint/erc20_nnn.git repo`

Cloning into 'repo'...

truffle-teams-ci: Executing build command `git fetch origin 09b727b6dd71e721a8acbab9ce4c585f59565407`

From https://github.com/overqint/erc20_nnn
* branch 09b727b6dd71e721a8acbab9ce4c585f59565407 -> FETCH_HEAD

truffle-teams-ci: Executing build command `git -c advice.detachedHead=false checkout FETCH_HEAD`

HEAD is now at 09b727b Token Transfer fee message corrected

truffle-teams-ci: Preparing your repo...

truffle-teams-ci: Adjusting the `networks` option in the Truffle config to support Truffle Teams...

truffle-teams-ci: Executing build command `npm install`


> bufferutil@4.0.2 install /home/builduser/teams_workingdir/repo/node_modules/bufferutil
> node-gyp-build


> keccak@3.0.1 install /home/builduser/teams_workingdir/repo/node_modules/keccak
> node-gyp-build || exit 0


> secp256k1@4.0.2 install /home/builduser/teams_workingdir/repo/node_modules/secp256k1
> node-gyp-build || exit 0


> utf-8-validate@5.0.3 install /home/builduser/teams_workingdir/repo/node_modules/utf-8-validate
> node-gyp-build


> node-hid@0.7.9 install /home/builduser/teams_workingdir/repo/node_modules/node-hid
> prebuild-install || node-gyp rebuild

prebuild-install WARN install libusb-1.0.so.0: cannot open shared object file: No such file or directory
make: Entering directory '/home/builduser/teams_workingdir/repo/node_modules/node-hid/build'
CC(target) Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o
../hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
#include <libudev.h>
^~~~~~~~~~~
compilation terminated.
hidapi-linux-hidraw.target.mk:103: recipe for target 'Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o' failed
make: Leaving directory '/home/builduser/teams_workingdir/repo/node_modules/node-hid/build'
make: *** [Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/home/builduser/.nvm/versions/node/v10.23.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack at ChildProcess.emit (events.js:198:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-1026-azure
gyp ERR! command "/home/builduser/.nvm/versions/node/v10.23.1/bin/node" "/home/builduser/.nvm/versions/node/v10.23.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/builduser/teams_workingdir/repo/node_modules/node-hid
gyp ERR! node -v v10.23.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.7.9 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@0.7.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/builduser/.npm/_logs/2021-01-12T16_01_25_143Z-debug.log
```

**Comment by danielddemissie** [comment]
I had this same problem when I tried to install the use-wallet package but the problem is the package libudev.h is not found on your system you can simply add it using this command

sudo apt-get install libudev-dev

and it should work.
